import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import yasVel from "../../public/yasuoOeste.jpg";
import yasPro from "../../public/yasuoProjeto.jpg";
import CardSkin from "@/components/CardSkin";
import CardInfo from "@/components/CardInfo";

export default function Home() {
  let icon = "";
  let infoIcon = "";
  let iconSkinType = "yasVel";

  const [card, setCard] = useState("yasVel");

  const alterCard = () => {
    if (card == "yasVel") {
      setCard("yasPro");
    } else {
      setCard("yasVel");
    }
  };

  if (card == "yasVel") {
    icon = yasVel;
    infoIcon =
      "Yasuo Velho Oeste é uma skin do Yasuo lançada em 2016. Uma das melhores skins do Yasuo, com um tema de faroeste a espada dele tem uma pistola insano";
    iconSkinType = "Velho Oeste";
  } else {
    icon = yasPro;
    infoIcon =
      "Yasuo Projeto é uma skin do Yasuo lançada em 2017. Uma das skins mais mids do Yasuo, serio voce so usa isso se n tiver outra";
    iconSkinType = "Projeto";
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <header>
        <h1>exemplo de useState mudando uma imagem</h1>
      </header>

      <div>
        <main className={styles.main}>
          <button className={styles.btn} onClick={alterCard}>
            mudar skin
          </button>
          <CardSkin icon={icon} />
          <CardInfo infoIcon={infoIcon} iconSkinType={iconSkinType} />
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </div>
  );
}
