import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState} from "react";
import yasVel from ".public/yasuoOeste.jpg";
import yasPro from ".public/yasuoProjeto.jpg";

export default function Home() {

  let icon = ''
  let infoIcon = ''
  let iconSkinType = 'yasVel'

  const [card, setCard] = useState('yasVel');

  const alterCard = () => {
    if (card == "yasVel") {
      setCard("yasPro"); 
    } else {
      setCard("yasVel");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <main className={styles.main}></main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </div>
  );
}
